version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing kubectl"
      - curl -LO "https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo "Updating kubeconfig for EKS"
      - aws eks update-kubeconfig --name eks-cluster --region eu-west-1
  build:
    commands:
      - echo "Applying Kubernetes manifests"
      - kubectl apply -f pv-pvc.yml
      - kubectl apply -f statefulset.yml
      - kubectl apply -f hpa.yml
artifacts:
  files:
    - '**/*'
