---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world
spec:
  serviceName: "hello-world-service"
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: web
        image: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        volumeMounts:
        - name: hello-storage
          mountPath: /usr/share/nginx/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'Hello, World!' > /usr/share/nginx/html/index.html"]
  volumeClaimTemplates:
  - metadata:
      name: hello-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi